server:
  port: 5555

  ssl:
    key-store: certs/proarchskeystore.p12
    key-store-password: proarchs
    keyStoreType: PKCS12
    keyAlias: proarchs
  
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.toystore.ecomm.zuulsvr: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: https://localhost:8761/eureka/


zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    user-management-service: /users/**
    generic-api-client: /client/**
    config-repo-service: /config/**
    tenant-management-service: /tms/**
  sensitiveHeaders: Cookie,Set-Cookie
  
#signing:
  #key: alteredcarbons1e7